### ISSUE TITLE
videoview.setVideoURI()切换播放源崩溃

### ISSUE THREAD

**Issue by HeroYiu** [easefun/polyv-android-sdk-2.0-demo#1]
使用videoView.setVideoURI（oldUri）播放，第一次正常，切换视频后，先调用videoView.release();然后再videoView.setVideoURI（newUri）时崩溃。注释掉videoView.release()，切换视频播放正常。
只是把demo中PolyvPlayerActivity的videoView.setVid（）换成了videoView.setVideoURI（）。
错误日志：
07-05 15:09:34.579 2641-4822/com.easefun.polyvsdk D/IJKMEDIA: IjkMediaPlayer_reset
07-05 15:09:34.579 2641-4822/com.easefun.polyvsdk D/IJKMEDIA: IjkMediaPlayer_release
07-05 15:09:34.579 2641-4822/com.easefun.polyvsdk D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
07-05 15:09:34.580 2641-4822/com.easefun.polyvsdk D/IJKMEDIA: ffpipeline_set_surface()
07-05 15:09:34.581 2641-4822/com.easefun.polyvsdk D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
07-05 15:09:34.581 2641-4822/com.easefun.polyvsdk D/IJKMEDIA: ijkmp_shutdown_l()
07-05 15:09:34.581 2641-4822/com.easefun.polyvsdk D/IJKMEDIA: wait for read_tid
07-05 15:09:34.581 2641-4828/com.easefun.polyvsdk D/IJKMEDIA: message_loop exit
07-05 15:09:34.581 2641-4828/com.easefun.polyvsdk I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4828]
07-05 15:09:34.581 2641-4831/com.easefun.polyvsdk I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4831]
07-05 15:09:34.582 2641-4830/com.easefun.polyvsdk I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4830]
07-05 15:09:34.582 2641-5024/com.easefun.polyvsdk I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [5024]
07-05 15:09:34.585 2641-2641/com.easefun.polyvsdk E/tag: play startNow
07-05 15:09:34.587 2641-2641/com.easefun.polyvsdk D/IJKMEDIA: IjkMediaPlayer_reset
07-05 15:09:34.587 2641-2641/com.easefun.polyvsdk D/IJKMEDIA: IjkMediaPlayer_release
07-05 15:09:34.587 2641-2641/com.easefun.polyvsdk D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
07-05 15:09:34.587 2641-2641/com.easefun.polyvsdk D/IJKMEDIA: ffpipeline_set_surface()
07-05 15:09:34.587 2641-2641/com.easefun.polyvsdk D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
07-05 15:09:34.587 2641-2641/com.easefun.polyvsdk D/IJKMEDIA: ijkmp_shutdown_l()
07-05 15:09:34.591 2641-2641/com.easefun.polyvsdk D/IJKMEDIA: wait for read_tid
07-05 15:09:34.592 2641-5031/com.easefun.polyvsdk I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [5031]
07-05 15:09:34.609 543-2573/? E/AudioFlinger: open /proc/2641/cmdline error
07-05 15:09:34.609 543-2573/? I/AudioFlinger: setAppName(), name=[], active=[0]
07-05 15:09:34.609 543-2573/? V/EffectDiracSound: DiracSound_command() start, cmdCode=23
07-05 15:09:34.609 543-2573/? V/EffectDiracSound: DiracSound_Command EFFECT_CMD_SET_APP_NAME: stream=3, name=-
07-05 15:09:34.610 2641-5023/com.easefun.polyvsdk I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [5023]
                                                              
                                                              
                                                              --------- beginning of crash
07-05 15:09:34.614 2641-4822/com.easefun.polyvsdk A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x64 in tid 4822 (pool-3-thread-1)
                                                          
                                                          [ 07-05 15:09:34.620   402:  402 W/         ]
                                                          debuggerd: handling request: pid=2641 uid=15154 gid=15154 tid=4822
07-05 15:09:34.628 543-685/? V/audio_hw_primary: out_get_latency: Latency 100
07-05 15:09:34.638 543-685/? V/audio_hw_primary: out_get_latency: Latency 100
07-05 15:09:34.648 543-685/? V/audio_hw_primary: out_get_latency: Latency 100
07-05 15:09:34.658 543-685/? V/audio_hw_primary: out_get_latency: Latency 100
07-05 15:09:34.668 543-685/? V/audio_hw_primary: out_get_latency: Latency 100
07-05 15:09:34.678 543-685/? V/audio_hw_primary: out_get_latency: Latency 100
07-05 15:09:34.688 543-685/? V/audio_hw_primary: out_get_latency: Latency 100
07-05 15:09:34.698 543-685/? V/audio_hw_primary: out_get_latency: Latency 100
07-05 15:09:34.708 543-685/? V/audio_hw_primary: out_get_latency: Latency 100
07-05 15:09:34.718 543-685/? V/audio_hw_primary: out_get_latency: Latency 100
07-05 15:09:34.728 543-685/? V/audio_hw_primary: out_get_latency: Latency 100
07-05 15:09:34.737 5267-5267/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-05 15:09:34.737 5267-5267/? A/DEBUG: Build fingerprint: 'Xiaomi/leo/leo:7.0/NRD90M/V8.2.3.0.NXHCNEC:user/release-keys'
07-05 15:09:34.737 5267-5267/? A/DEBUG: Revision: '0'
07-05 15:09:34.737 5267-5267/? A/DEBUG: ABI: 'arm64'
07-05 15:09:34.737 5267-5267/? A/DEBUG: pid: 2641, tid: 4822, name: pool-3-thread-1  >>> com.easefun.polyvsdk <<<
07-05 15:09:34.737 5267-5267/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x64
07-05 15:09:34.737 5267-5267/? A/DEBUG:     x0   0000007f62750000  x1   0000000000000000  x2   ffffffffffffffc0  x3   0000000000000000
07-05 15:09:34.738 5267-5267/? A/DEBUG:     x4   0000000000000000  x5   0000000000000000  x6   0000007f5e4ec7a0  x7   0000000400000000
07-05 15:09:34.738 5267-5267/? A/DEBUG:     x8   0000140400001400  x9   0000000c00000008  x10  0000140c00001408  x11  0000280400002800
07-05 15:09:34.738 5267-5267/? A/DEBUG:     x12  00003c0400003c00  x13  0000280c00002808  x14  00003c0c00003c08  x15  0000000000001fe3
07-05 15:09:34.738 5267-5267/? A/DEBUG:     x16  0000007f61d6cd68  x17  0000007f84992b08  x18  0000000000000000  x19  0000007f5e4ec000
07-05 15:09:34.738 5267-5267/? A/DEBUG:     x20  0000007f5e4e5000  x21  0000007f5e4e5000  x22  0000000000000000  x23  0000007f5e3d1000
07-05 15:09:34.738 5267-5267/? A/DEBUG:     x24  0000007f5e4ed000  x25  0000007f5e3d0620  x26  0000007f5e4ec620  x27  0000007f5e3d0000
07-05 15:09:34.738 5267-5267/? A/DEBUG:     x28  0000007f5e3d1370  x29  0000007f63b59390  x30  0000007f61a5762c
07-05 15:09:34.738 5267-5267/? A/DEBUG:     sp   0000007f63b59220  pc   0000007f61a54d54  pstate 0000000060000000
07-05 15:09:34.739 543-685/? V/audio_hw_primary: out_get_latency: Latency 100
07-05 15:09:34.741 5267-5267/? A/DEBUG: backtrace:
07-05 15:09:34.742 5267-5267/? A/DEBUG:     #00 pc 0000000000104d54  /data/app/com.easefun.polyvsdk-1/lib/arm64/libijkffmpeg.so
07-05 15:09:34.742 5267-5267/? A/DEBUG:     #01 pc 0000000000107628  /data/app/com.easefun.polyvsdk-1/lib/arm64/libijkffmpeg.so (ff_h264_update_thread_context+548)
07-05 15:09:34.748 543-685/? V/audio_hw_primary: out_get_latency: Latency 100

**Comment by tanqu2013** [comment]
好的，感谢反馈，我们会进行检查。

**Comment by tanqu2013** [comment]
我们已经定位到错误，将在下个版本修复。

**Comment by HeroYiu** [comment]
谢谢，希望修复版在我们应用测试前出来，到时直接替换使用。
