### ISSUE TITLE
无法依赖是为什么

### ISSUE THREAD

**Issue by sushanqiang** [easefun/polyv-android-sdk-2.0-demo#11]
com.easefun.polyv:polyvPlayer:2.5.1和com.easefun.polyv:polyvPlayer:2.5.0 都下载不了

**Comment by df8969386** [comment]
建议下载com.easefun.polyv:polyvPlayer:2.5.2版本 优化了一些播放的问题

**Comment by df8969386** [comment]
请问是报什么错误 2.5.1是可以正常下载的

**Comment by sushanqiang** [comment]
我把  https://dl.bintray.com/polyv/android  改成 http 就可以了
