### ISSUE TITLE
so文件重复

### ISSUE THREAD

**Issue by dingdaidao** [easefun/polyv-android-sdk-2.0-demo#13]
api ('com.easefun.polyv:polyvPlayer:2.5.2')
            {
                exclude group: 'com.tencent.bugly'
                exclude group: 'tv.danmaku.ijk.media'
            }
里面还有ijk的so文件冲突，能不能把ijk的so用远程依赖，本地依赖ex不掉

**Comment by tanqu2013** [comment]
so文件不能排除，否则无法播放加密视频。如果你是需要整合两个播放器，你联系一下技术支持来解决这个问题。
