### ISSUE TITLE
播放音频,setOnCompletionListener回调有误差

### ISSUE THREAD

**Issue by ddt2016** [easefun/polyv-android-sdk-2.0-demo#15]
比如音频16分钟,基本上要17 18分钟后才触发setOnCompletionListener,视频无影响

**Comment by tanqu2013** [comment]
请提供一下音频地址，如果是使用音频模式播放的，请提供一下vid。

**Comment by ddt2016** [comment]
c21c20bea1204fd76fa2cc972dc53a58_c

**Comment by ddt2016** [comment]
回个话啊

**Comment by ddt2016** [comment]
加密的音频来的

**Comment by tanqu2013** [comment]
音频文件建议源文件播放，音频文件加密转码后时长可能跟原来时长不同。
