### ISSUE TITLE
远程maven仓库下载依赖失败问题

### ISSUE THREAD

**Issue by yanerchuang** [easefun/polyv-android-sdk-2.0-demo#17]
https://dl.bintray.com/polyv/android 该仓库下载文件常常出现下载失败问题，每次更新版本都要耗费大量时间来解决下载的问题，能否提供一个国内的仓库，优化该问题？

**Comment by SHLURENJIA** [comment]
你好，v2.15.2起已经可以通过阿里云镜和阿里云效下载。
