### ISSUE TITLE
咱们能提供React-native  的SDK？

### ISSUE THREAD

**Issue by coolsnow77** [easefun/polyv-android-sdk-2.0-demo#2]
咱们能提供React-native  的SDK？
现在在用的项目是React-native 开发的app， 使用的咱们的Polyv 多终端播放代码， 采用WebView 方式播放， ios 下播放视频可以全屏， android 下播放视频不能全屏。
也咨询了下咱们的技术，咱们的技术没有给回复。请问该怎么解决，谢谢。

**Comment by tanqu2013** [comment]
React-native的SDK暂时不会支持。
关于WebView全屏播放的问题，你有没有做这个功能的开发。

**Comment by coolsnow77** [comment]
@tanqu2013 , WebView 的全屏， 我暂时这样做的。 点击全屏播放的时候， 视频播放窗口所有的外围view 宽和高都设置为0， 然后将playvObject 的width 设置为window.screen.width 这样就可以了。
但是咱们的全屏播放事件是？如何触发。。（采用webView 的postMessage 和onMessage 相互和webview里面的网页polyvObject window.postMessage 通信）

**Comment by coolsnow77** [comment]
@tanqu2013 如果咱们支持react-native 的SDK ， 相信Polyv 会更利于开发者开发， 毕竟现在react-native 也是主流开发app的。。。 还是请考虑一下。。。
