### ISSUE TITLE
当使用 gradle 6.5.1 ，AGP 4.1.3时 无法编译通过

### ISSUE THREAD

**Issue by stepforfuture** [easefun/polyv-android-sdk-2.0-demo#23]
如题 ，我们一直使用保利威版本是2.13.x，今天发现更新后，火速同步你们最新版本
我们使用的 gradle和 android gradle plugin 版本如下
**gradle/wrapper/gradle-wrapper.properties**
`distributionBase=GRADLE_USER_HOME`
`distributionPath=wrapper/dists`
`zipStoreBase=GRADLE_USER_HOME`
`zipStorePath=wrapper/dists`
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.5.1-all.zip`
项目根目录下**build.gradle**
` dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
}`

报错信息如下
`* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.aliyun.ams:alicloud-android-utdid:1.1.5.4.
     Searched in the following locations:
       - http://maven.aliyun.com/nexus/content/groups/public/com/aliyun/ams/alicloud-android-utdid/1.1.5.4/alicloud-android-utdid-1.1.5.4.pom
       - https://jcenter.bintray.com/com/aliyun/ams/alicloud-android-utdid/1.1.5.4/alicloud-android-utdid-1.1.5.4.pom
       - http://maven.aliyun.com/nexus/content/repositories/releases/com/aliyun/ams/alicloud-android-utdid/1.1.5.4/alicloud-android-utdid-1.1.5.4.pom
       - https://repo.maven.apache.org/maven2/com/aliyun/ams/alicloud-android-utdid/1.1.5.4/alicloud-android-utdid-1.1.5.4.pom
       - https://maven.aliyun.com/repository/public/com/aliyun/ams/alicloud-android-utdid/1.1.5.4/alicloud-android-utdid-1.1.5.4.pom
       - file:/Users/tianjinyong/Desktop/work_dir/polyv-android-sdk-2.0-demo/app/libs/alicloud-android-utdid-1.1.5.4.jar
       - file:/Users/tianjinyong/Desktop/work_dir/polyv-android-sdk-2.0-demo/app/libs/alicloud-android-utdid.jar
     Required by:
         project :app > net.polyv.android:polyvPlayer:2.15.2 > net.polyv.android:plvHttpDns:1.3.2.3-p1 > com.aliyun.ams:alicloud-android-httpdns:1.3.2.3 > com.aliyun.ams:alicloud-android-beacon:1.0.4.3
   > Could not find com.aliyun.ams:alicloud-android-utdid:1.1.5.4.
     Searched in the following locations:
       - http://maven.aliyun.com/nexus/content/groups/public/com/aliyun/ams/alicloud-android-utdid/1.1.5.4/alicloud-android-utdid-1.1.5.4.pom
       - https://jcenter.bintray.com/com/aliyun/ams/alicloud-android-utdid/1.1.5.4/alicloud-android-utdid-1.1.5.4.pom
       - http://maven.aliyun.com/nexus/content/repositories/releases/com/aliyun/ams/alicloud-android-utdid/1.1.5.4/alicloud-android-utdid-1.1.5.4.pom
       - https://repo.maven.apache.org/maven2/com/aliyun/ams/alicloud-android-utdid/1.1.5.4/alicloud-android-utdid-1.1.5.4.pom
       - https://maven.aliyun.com/repository/public/com/aliyun/ams/alicloud-android-utdid/1.1.5.4/alicloud-android-utdid-1.1.5.4.pom
       - file:/Users/tianjinyong/Desktop/work_dir/polyv-android-sdk-2.0-demo/app/libs/alicloud-android-utdid-1.1.5.4.jar
       - file:/Users/tianjinyong/Desktop/work_dir/polyv-android-sdk-2.0-demo/app/libs/alicloud-android-utdid.jar
     Required by:
         project :app > net.polyv.android:polyvPlayer:2.15.2 > net.polyv.android:plvHttpDns:1.3.2.3-p1 > com.aliyun.ams:alicloud-android-httpdns:1.3.2.3 > com.aliyun.ams:alicloud-android-utils:1.1.6.4 > com.aliyun.ams:alicloud-android-ut:5.4.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`

**我也使用你们的demo代码尝试过，当gradle版本为4.10.2，AGP版本为3.0.1时，确实可以编译成功；但是更新gradle版本到6.5.1，AGP版本为4.1.3后 就会报错如上？请问这种如何处理？ 降低gradle版本和AGP版本会导致应该app构建速度变慢，也无法使用到最新的功能**

**Comment by Yukino0812** [comment]
阿里的alicloud-android-utdid-1.1.5.4不带pom.xml文件导致gradle 6.x及以上版本无法拉取依赖
改用1.5.2版本即可
```groovy
implementation ('net.polyv.android:polyvPlayer:2.15.2') {
    // 排除SDK内的utdid
    exclude group:'com.aliyun.ams',module:'alicloud-android-utdid'
}
// 添加1.5.2的utdid
api 'com.aliyun.ams:alicloud-android-utdid:1.5.2'
```
如果仍报错，其他的功能包（如polyvDownload、polyvUpload、polyvSub）也exclude一下utdid包就好
