### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by stepforfuture** [easefun/polyv-android-sdk-2.0-demo#24]
我更新开启混淆后出现，报错
`
Expected [access-flag]* void <init> at /Users/tianjinyong/.gradle/caches/transforms-2/files-2.1/6eb3953875f71a5b25dbbb485fde323c/jetified-polyvPlayer-2.15.2/proguard.txt:95:42
    public PolyvAuxiliaryVideoView <init>;
`

我就是使用你们demo一样的有问题，我下载你们demo，gradle配置为 6.5.1，agp为4.1.3； 设置 minifyEnabled true，也会报上面的错误，是不是sdk里面的混淆配置有问题啊？

**Comment by SHLURENJIA** [comment]
你好，v2.15.3已修复此问题，可更新sdk
