### ISSUE TITLE
重复播放问题

### ISSUE THREAD

**Issue by wxmylife** [easefun/polyv-android-sdk-2.0-demo#25]
问题：视频播放完成后，点击播放按钮，调用 start 方法后，setOnPreparedListener 回调不触发，如何判断视频重复播放？

**Comment by SHLURENJIA** [comment]
setOnPreparedListener，往往只在视频加载完成之后才会回调。重复播放是不会再次出发的。
可以监听 IPolyvOnCompletionListener2 接口回调，他将在视频播放完成后回调 onCompletion() 方法，可以通过记录标志位等方法，判断重复播放。
