### ISSUE TITLE
bugly

### ISSUE THREAD

**Issue by wodx521** [easefun/polyv-android-sdk-2.0-demo#26]
bugly 冲突怎么解决, 要集成自动升级, crashreport_upgrade 冲突, 无法编译通过

**Comment by luayua** [comment]
implementation('net.polyv.android:polyvPlayer:2.16.3') {
        exclude group: 'com.tencent.bugly', module: 'crashreport'
    }

**Comment by wodx521** [comment]
这样配置不起作用, 我试过了, 还是会引入低版本的库, 最后解决办法是在build.gradle末尾加上`configurations{
    all*.exclude group:'com.tencent.bugly', module:'crashreport'
}` 之后就可以编译通过了
