### ISSUE TITLE
项目无法运行，那几个包一直下载不下来

### ISSUE THREAD

**Issue by sushanqiang** [easefun/polyv-android-sdk-2.0-demo#27]
活久见，Could not find com.easefun.polyv:polyvSDKCloudClass:0.16.3,
Could not GET 'https://dl.bintray.com/polyv/android/com/easefun/polyv/polyvSDKCloudClass/0.16.3/polyvSDKCloudClass-0.16.3.aar'. Received status code 403 from server: Forbidden

**Comment by SHLURENJIA** [comment]
你好，polyvSDKCloudClass是我们的[云课堂直播项目](https://github.com/polyv/polyv-android-cloudClass-sdk-demo)的SDK，这个仓库是点播的。

库拉不下来的原因是因为以前用的是bintray，该源仓库被停用，后来改为阿里云仓库。其中groupID从com.easefun.polyv变更为了net.polyv.android。所以您这边拉不下来。在云课堂直播项目的最新的release中有说明，请查看后修改。

此外，建议您升级到[多场景直播项目](https://github.com/polyv/polyv-android-livescenes-sdk-demo)
