### ISSUE TITLE
2021-10-28 polyv-android-sdk-2.0.0-demo v2.16.5    更新依赖失败    

### ISSUE THREAD

**Issue by hhszzheng** [easefun/polyv-android-sdk-2.0-demo#28]
Could not GET 'https://dl.bintray.com/umsdk/release/com/aliyun/ams/alicloud-android-utdid/1.1.5.4/alicloud-android-utdid-1.1.5.4.pom'. Received status code 403 from server: Forbidden

**Comment by SHLURENJIA** [comment]
你好，这个可能是阿里那边pom异常导致无法拉取此版本。其他版本是正常的。可以尝试如下修改：

`
api ('net.polyv.android:polyvPlayer:2.16.5') {   // 此处仅做举例，SDK包及版本号填写开发者原来使用的SDK及版本号
    exclude group:'com.aliyun.ams',module:'alicloud-android-utdid'
}
api 'com.aliyun.ams:alicloud-android-utdid:1.5.2'   // 1.5.2版本经测试可用，开发者也可以使用其他版本
`
