### ISSUE TITLE
经常卡在缓冲中

### ISSUE THREAD

**Issue by HeroYiu** [easefun/polyv-android-sdk-2.0-demo#3]
如果用seekto 更容易发生卡在缓冲中的现象，就是一直转圈圈。
另外在log中发现如下提示，请问是网络原因还是什么原因造成的卡死：
 ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
07-09 14:55:31.145 3709-27252/com.easefun.polyvsdk D/IJKMEDIA: FFP_MSG_SEEK_COMPLETE:
07-09 14:55:31.145 3709-27254/com.easefun.polyvsdk I/IJKMEDIA: HLS request for url 'http://ws36.videocc.net/78047b73a5/1499393161000/8/1b/00/58_2/78047b73a5befefd8b6685d0791b0058_2_4.ts', offset 0, playlist 0
07-09 14:55:31.213 3709-27254/com.easefun.polyvsdk W/**## IJKMEDIA: the user-agent option is deprecated, please use user_agent option**
07-09 14:55:31.213 3709-27254/com.easefun.polyvsdk D/IJKMEDIA: request: GET /78047b73a5/1499393161000/8/1b/00/58_2/78047b73a5befefd8b6685d0791b0058_2_4.ts HTTP/1.1
                                                               User-Agent: polyv-android-sdk2.0.2-20170621
                                                               Accept: */*
                                                               Connection: close
                                                               Host: ws36.videocc.net
                                                               Icy-MetaData: 1
07-09 14:55:47.502 1532-2115/system_process D/NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 101]: OfflineState{ when=-99ms what=532488 arg2=1 target=com.android.internal.util.StateMachine$SmHandler }
07-09 14:55:47.502 1532-2115/system_process D/NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 101]: DefaultState{ when=-99ms what=532488 arg2=1 target=com.android.internal.util.StateMachine$SmHandler }
07-09 14:55:47.502 1532-2115/system_process D/NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 101]: Forcing reevaluation
07-09 14:55:47.502 1532-2115/system_process D/NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 101]: EvaluatingState{ when=0 what=532486 arg1=9 target=com.android.internal.util.StateMachine$SmHandler }
07-09 14:55:47.502 1532-2115/system_process D/NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 101]: Checking http://connectivitycheck.android.com/generate_204 on epc.tmobile.com
07-09 14:55:47.505 1532-2115/system_process D/NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 101]: Probably not a portal: exception java.net.UnknownHostException: Unable to resolve host "connectivitycheck.android.com": No address associated with hostname
07-09 14:55:47.505 1532-1603/system_process D/ConnectivityService: setProvNotificationVisibleIntent: E visible=false networkType=0 extraInfo=null

**Comment by tanqu2013** [comment]
从日志看是网络原因没有加载到第5片ts，在服务器查看访问记录资源的长度获取也不稳定，我这边测试这个视频没有出现卡死的情况，你可以提供一下你卡的手机的ip，我继续查一下。
http://www.wangsutong.com/wstCeba/local/local-test.action 浏览器打开这个链接可以看到ip。
